spring.application.name=UserAuuthenticatiom
spring.security.user.name=Dhanush
spring.security.user.password=1111
service.servlet.session.cookie.same-site=strict

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/forsecurityy
spring.datasource.username=root
spring.datasource.password=83744
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect